name: GitHub Actions Manually
on: [workflow_dispatch]
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
           node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        run: npx cypress run --record --key acf5a95a-f5fe-4d53-818a-a6afa18e512c