name: GitHub Actions Manually
on: [workflow_dispatch]
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      job: [0, 1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
           node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        run: npx cypress run
