name: Github-actions-pr-to-master
on:
  pull_request:
  push:
    branches: master
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
           node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        run: npx cypress run
